# Generated by Django 2.2.6 on 2019-12-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Company', models.CharField(default='Unknown', max_length=50)),
                ('Newspaper', models.FileField(upload_to='../media/')),
                ('Year', models.IntegerField(default=None)),
                ('User', models.CharField(max_length=100)),
            ],
        ),
    ]
